### ISSUE TITLE
Remove use of PODS_ROOT from the podspec

### ISSUE THREAD

**Issue by kylef** [AntonPalich/Flurry#18]
`$PODS_ROOT` has been deprecated in CocoaPods and you should instead be using `vendored_libraries`. See https://github.com/CocoaPods/CocoaPods/issues/2449#issuecomment-55348373.

Raising this here because an issue was filed and it looks with this podspec not working due to this. https://github.com/CocoaPods/CocoaPods/issues/2018

**Comment by irichardson** [comment]
Trying to add 5.4.0 and I am still seeing an issue with the .a file. Has there been a change with the new version?
