### ISSUE TITLE
Version 6 of the flurry SDK is available

### ISSUE THREAD

**Issue by combinatorial** [AntonPalich/Flurry#23]
Thanks for maintaining the podfile for flurry, can you update to the latest Flurry SDK?

**Comment by CraigSiemens** [comment]
Any idea when this will be updated?

**Comment by combinatorial** [comment]
I've emailed support@flurry.com to ask for an official pod for their SDK. They replied that they will bring it up in their next feature meeting. Maybe if enough people do the same we can raise it up their list of priorities.

**Comment by CraigSiemens** [comment]
Cool, I just did the same thing. Hopefully they'll add it. :smile:

**Comment by nafu** [comment]
:+1:

**Comment by shams-ahmed** [comment]
+1

**Comment by AntonPalich** [comment]
Sorry for the delay. Official support is a good news. Waiting for this too.
